<?php if ( ICL_LANGUAGE_CODE=='en' ) :?>
<option value="Riyadh">Riyadh</option>
<option value="Diriyah">Diriyah</option>
<option value="Al-Kharj">Al-Kharj</option>
<option value="Dawadmi">Dawadmi</option>
<option value="Al Majma'ah">Al Majma'ah</option>
<option value="Al-Quway'iyah">Al-Quway'iyah</option>
<option value="Wadi ad-Dawasir">Wadi ad-Dawasir</option>
<option value="Al Aflaj">Al Aflaj</option>
<option value="Al Zulfi">Al Zulfi</option>
<option value="Shuqrah">Shuqrah</option>
<option value="Hotat Bani Tamim">Hotat Bani Tamim</option>
<option value="Afif">Afif</option>
<option value="As Sulayyil">As Sulayyil</option>
<option value="Dhurma">Dhurma</option>
<option value="Al-Muzahmiyya">Al-Muzahmiyya</option>
<option value="Rumah">Rumah</option>
<option value="Thadig">Thadig</option>
<option value="Huraymila">Huraymila</option>
<option value="Al Hariq">Al Hariq</option>
<option value="Al-Ghat">Al-Ghat</option>
<option value="Mecca">Mecca</option>
<option value="Jeddah">Jeddah</option>
<option value="Ta'if">Ta'if</option>
<option value="Al Qunfudhah">Al Qunfudhah</option>
<option value="Al Lith">Al Lith</option>
<option value="Rabigh">Rabigh</option>
<option value="Al Jumum">Al Jumum</option>
<option value="Khulays">Khulays</option>
<option value="Al Kamil">Al Kamil</option>
<option value="Al Khurmah">Al Khurmah</option>
<option value="Ranyah">Ranyah</option>
<option value="Turubah">Turubah</option>
<option value="Medina">Medina</option>
<option value="Yanbu">Yanbu</option>
<option value="Al-`Ula">Al-`Ula</option>
<option value="Mahd adh Dhahab">Mahd adh Dhahab</option>
<option value="Badr">Badr</option>
<option value="Khaybar">Khaybar</option>
<option value="Al Hinakiyah">Al Hinakiyah</option>
<option value="Buraidah">Buraidah</option>
<option value="Unaizah">Unaizah</option>
<option value="Ar Rass">Ar Rass</option>
<option value="Al Mithnab">Al Mithnab</option>
<option value="Al Bukayriyah">Al Bukayriyah</option>
<option value="Al Badayea">Al Badayea</option>
<option value="Asyah">Asyah</option>
<option value="Al Nabhaniyah">Al Nabhaniyah</option>
<option value="Uyun AlJiwa">Uyun AlJiwa</option>
<option value="Riyadh Al Khabra">Riyadh Al Khabra</option>
<option value="Al Shimasiyah">Al Shimasiyah</option>
<option value="Dammam">Dammam</option>
<option value="Al Ahsa">Al Ahsa</option>
<option value="Hafar Al-Batin">Hafar Al-Batin</option>
<option value="Jubail">Jubail</option>
<option value="Qatif">Qatif</option>
<option value="Khobar">Khobar</option>
<option value="Khafji">Khafji</option>
<option value="Ras Tanura">Ras Tanura</option>
<option value="Abqaiq">Abqaiq</option>
<option value="Al Nairyah">Al Nairyah</option>
<option value="Qaryat al-Ulya">Qaryat al-Ulya</option>
<option value="Abha">Abha</option>
<option value="Khamis Mushait">Khamis Mushait</option>
<option value="Bisha">Bisha</option>
<option value="Al-Namas">Al-Namas</option>
<option value="Muhayil">Muhayil</option>
<option value="Sarat Abidah">Sarat Abidah</option>
<option value="Tathlith">Tathlith</option>
<option value="Rojal">Rojal</option>
<option value="Ahad Rafidah">Ahad Rafidah</option>
<option value="Dhahran Al Janub">Dhahran Al Janub</option>
<option value="Balqarn">Balqarn</option>
<option value="Al Majaridah">Al Majaridah</option>
<option value="Tabuk">Tabuk</option>
<option value="Al Wajh">Al Wajh</option>
<option value="Duba">Duba</option>
<option value="Tayma">Tayma</option>
<option value="Umluj">Umluj</option>
<option value="Haql">Haql</option>
<option value="Ha'il">Ha'il</option>
<option value="Baqaa">Baqaa</option>
<option value="Al Khazaiah">Al Khazaiah</option>
<option value="Al Shinan">Al Shinan</option>
<option value="Arar">Arar</option>
<option value="Rafha">Rafha</option>
<option value="Turaif">Turaif</option>
<option value="Jizan">Jizan</option>
<option value="Sabya">Sabya</option>
<option value="Abu `Arish">Abu `Arish</option>
<option value="Samtah">Samtah</option>
<option value="Al Harth">Al Harth</option>
<option value="Damad">Damad</option>
<option value="Al Reeth">Al Reeth</option>
<option value="Baish">Baish</option>
<option value="Farasan">Farasan</option>
<option value="Al Dayer">Al Dayer</option>
<option value="Ahad al Masarihah">Ahad al Masarihah</option>
<option value="Al Edabi">Al Edabi</option>
<option value="Al Aridhah">Al Aridhah</option>
<option value="Al Darb">Al Darb</option>
<option value="Najran">Najran</option>
<option value="Sharurah">Sharurah</option>
<option value="Hubuna">Hubuna</option>
<option value="Badr Al Janub">Badr Al Janub</option>
<option value="Yadamah">Yadamah</option>
<option value="Thar">Thar</option>
<option value="Khubash">Khubash</option>
<option value="Al Kharkhir">Al Kharkhir</option>
<option value="Al Bahah">Al Bahah</option>
<option value="Baljurashi">Baljurashi</option>
<option value="Al Mandaq">Al Mandaq</option>
<option value="Al Makhwah">Al Makhwah</option>
<option value="Al Aqiq">Al Aqiq</option>
<option value="Qilwah">Qilwah</option>
<option value="Al Qara">Al Qara</option>
<option value="Sakakah">Sakakah</option>
<option value="Qurayyat">Qurayyat</option>
<option value="Dumat al-Jandal">Dumat al-Jandal</option>
<?php else:?>
<option value=" الرياض   "> الرياض   </option>
<option value=" الدرعية "> الدرعية </option>
<option value=" الخرج "> الخرج </option>
<option value="الدوادمي ">الدوادمي </option>
<option value="المجمعة ">المجمعة </option>
<option value="القويعية ">القويعية </option>
<option value="وادي الدواسر ">وادي الدواسر </option>
<option value="الأفلاج ">الأفلاج </option>
<option value="الزلفي ">الزلفي </option>
<option value="شقرة ">شقرة </option>
<option value="حوطة بني تميم ">حوطة بني تميم </option>
<option value="عفيف ">عفيف </option>
<option value="السليل ">السليل </option>
<option value="ضرما ">ضرما </option>
<option value="المزاحمية ">المزاحمية </option>
<option value="رماح ">رماح </option>
<option value="ثادق ">ثادق </option>
<option value="حريميلة ">حريميلة </option>
<option value="الحارق ">الحارق </option>
<option value="الغاط ">الغاط </option>
<option value="مكة ">مكة </option>
<option value="جدة ">جدة </option>
<option value="الطائف ">الطائف </option>
<option value="القنفذة ">القنفذة </option>
<option value="الليث ">الليث </option>
<option value="رابغ ">رابغ </option>
<option value="الجموم ">الجموم </option>
<option value="خليص ">خليص </option>
<option value="الكامل ">الكامل </option>
<option value="الخرمة ">الخرمة </option>
<option value="رانية ">رانية </option>
<option value="تربة ">تربة </option>
<option value="المدينة المنورة ">المدينة المنورة </option>
<option value="ينبع ">ينبع </option>
<option value="العلا ">العلا </option>
<option value="مهد الدهب ">مهد الدهب </option>
<option value="بدر ">بدر </option>
<option value="خيبر ">خيبر </option>
<option value="الحناكية ">الحناكية </option>
<option value="بريدة ">بريدة </option>
<option value="عنيزة ">عنيزة </option>
<option value="الرس ">الرس </option>
<option value="المذنب ">المذنب </option>
<option value="البكيرية ">البكيرية </option>
<option value="البدائع ">البدائع </option>
<option value="الاسياح ">الاسياح </option>
<option value="النبهانية ">النبهانية </option>
<option value="عيون الجواء ">عيون الجواء </option>
<option value="رياض الخبراء ">رياض الخبراء </option>
<option value="الشماسية ">الشماسية </option>
<option value="الدمام ">الدمام </option>
<option value="الأحساء ">الأحساء </option>
<option value="حفر الباطن ">حفر الباطن </option>
<option value="الجبيل ">الجبيل </option>
<option value="القطيف ">القطيف </option>
<option value="الخبر ">الخبر </option>
<option value="الخفجي ">الخفجي </option>
<option value="رأس تنورة ">رأس تنورة </option>
<option value="ابقيق ">ابقيق </option>
<option value="النعيرية ">النعيرية </option>
<option value="قرية العليا ">قرية العليا </option>
<option value="أبها ">أبها </option>
<option value="خميس مشيط ">خميس مشيط </option>
<option value="بيشة ">بيشة </option>
<option value="النماص ">النماص </option>
<option value="محايل ">محايل </option>
<option value="سراة عبيدة ">سراة عبيدة </option>
<option value="تثليث ">تثليث </option>
<option value="روجال ">روجال </option>
<option value="احد رفيدة ">احد رفيدة </option>
<option value="ظهران الجنوب ">ظهران الجنوب </option>
<option value="بالقرن ">بالقرن </option>
<option value="المجاردة ">المجاردة </option>
<option value="تبوك ">تبوك </option>
<option value="الوجه ">الوجه </option>
<option value="ضبا ">ضبا </option>
<option value="تيماء ">تيماء </option>
<option value="أملج ">أملج </option>
<option value="حقل ">حقل </option>
<option value="حائل ">حائل </option>
<option value="البقعة ">البقعة </option>
<option value="الخزاعية ">الخزاعية </option>
<option value="الشنان ">الشنان </option>
<option value="عرعر ">عرعر </option>
<option value="رفحاء ">رفحاء </option>
<option value="طريف ">طريف </option>
<option value="جيزان ">جيزان </option>
<option value="صبيا ">صبيا </option>
<option value="أبو عريش ">أبو عريش </option>
<option value="صامطة ">صامطة </option>
<option value="الحارث ">الحارث </option>
<option value="داماد ">داماد </option>
<option value="الريث ">الريث </option>
<option value="بايش ">بايش </option>
<option value="فرسان ">فرسان </option>
<option value="الداير ">الداير </option>
<option value="أحد المسارحة ">أحد المسارحة </option>
<option value="العيدابي ">العيدابي </option>
<option value="العارضة ">العارضة </option>
<option value="الدرب ">الدرب </option>
<option value="نجران ">نجران </option>
<option value="شرورة ">شرورة </option>
<option value="حبونا ">حبونا </option>
<option value="بدر الجنوب ">بدر الجنوب </option>
<option value="يدامة ">يدامة </option>
<option value="ثار ">ثار </option>
<option value="خباش ">خباش </option>
<option value="الخرخير ">الخرخير </option>
<option value="الباحة ">الباحة </option>
<option value="بلجرشي ">بلجرشي </option>
<option value="المندق ">المندق </option>
<option value="المخواة ">المخواة </option>
<option value="العقيق ">العقيق </option>
<option value="قلوة ">قلوة </option>
<option value="القرع ">القرع </option>
<option value="سكاكا ">سكاكا </option>
<option value="القريات ">القريات </option>
<option value="دومة الجندل ">دومة الجندل </option>
<?php endif?>